export * from "./Login/LogIn.pages";
export * from "./About/About.pages";
export * from "./All-Products/AllProducts.pages";
export * from "./Basket-shopping/BasketShopping.pages";
export * from "./Blog/Blog.pages";
export * from "./Checkout/Checkout.pages";
export * from "./ContactUs/ContactUs.pages";
export { Home as default } from "./Home/Home.pages";
export * from "./Nofound/NotFound.pages";
export * from "./Orders/Orders.pages";
export * from "./Single-Product/SingleProduct.pages";
export * from "./Categories/Categories.pages";
export * from "./UserAccount/UserAccount.pages";
export * from "./Payment-page/Payment/Payment.pages";
export * from "./Payment-page/Payment-Failed/PaymentFaild.pages";
export * from "./Payment-page/Payment-Success/PaymentSuccess.pages";
